server:
  port: 7788
swagger:
  enabled: true #是否启用swagger
  title: 测试标题
  description: 在线文档
  version: 0.1
  #basePackage: com.mo.controller #不分组
  docket:
    user:
      title: 用户模块
      group: 用户模块组
      base-package: com.mo.controller.user
    menu:
      title: 菜单模块
      group: 菜单模块组
      base-package: com.mo.controller.menu
